/* THIS FILE IS AUTOMATICALLY GENERATED-- DO NOT MODIFY IT*/
package ca.weblite.codename1.cn1ml.demos;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.ui.table.*;
import com.codename1.ui.util.*;
class MainMenu {
private Container rootContainer;
private Resources resources;
public Container getRoot(){ if (rootContainer==null){ 
        try {rootContainer=buildUI();} catch (Exception ex){ex.printStackTrace();throw new RuntimeException(ex.getMessage());}} return rootContainer;}
private java.util.Map<String,Component> _nameIndex=new java.util.HashMap<String,Component>();
public Component get(String name){ getRoot(); return _nameIndex.get(name);}
private String[] menuItems;
public MainMenu(java.util.Map context){
menuItems = (String[])context.get("menuItems");
for (Object o : context.values()){ if (o instanceof Resources) resources=(Resources)o;}
}
private Container buildUI() throws Exception {
Container root = new Container();
BorderLayout rootLayout = new BorderLayout();
root.setLayout(rootLayout);
List node1 = new List();
node1.setName("menuList");
_nameIndex.put("menuList", node1);
init1_node1(node1, root);
if (root != node1.getParent()){
root.addComponent(BorderLayout.CENTER, node1);
}
return root;
}
public List getMenuList(){
      return (List)get("menuList");
      }
private void init1_node1(List self, Container parent){
self.setModel(new com.codename1.ui.list.DefaultListModel(menuItems));

}
}